### ISSUE TITLE
Expose the lower level builder api or similar

### ISSUE THREAD

**Issue by NZKoz** [MindscapeHQ/raygun4java#27] opened 2015-04-16 04:59 UTC
For various entirely valid but boring reasons, we can't use the Servlet submitter, what I'd like is an api which was slightly lower level.  Something like:

``` java
RaygunClient client = whatever.gimmeOne();
// later on
RaygunMessage message = client.buildRaygunMessage(throwable, servletRequest, whateverElse);
// on another thread
client.sendMessage(message)
```

**Comment by NZKoz** [comment] 2015-04-16 22:07
So my work around implementation looks like this.

```java

		try {
			RaygunMessage message;
			message = RaygunServletMessageBuilder.New()
					.SetRequestDetails(request)
					.SetEnvironmentDetails()
					.SetMachineName(InetAddress.getLocalHost().getHostName())
					.SetExceptionDetails(throwable)
					.SetClientDetails()
					.Build();
			this.executor.execute(new SubmitExceptionCommand(client, message));
		} catch (UnknownHostException e) {
			// error when handling errors, not much to do but log and fail
			e.printStackTrace();
		}
// 
	private final class SubmitExceptionCommand implements Runnable {
		public SubmitExceptionCommand(RaygunClient client, RaygunMessage message) {
			this.client = client;
			this.message = message;
		}
		private final RaygunClient client;
		private final RaygunMessage message;
		@Override
		public void run() {
			client.Post(message);
		}
	}

```

Three things are slightly annoying.  

1. I can't get the builder out of the client without duplicating the code.  Something like `.messageBuilderForException(` would help.
2. I can't add the servlet request to a non servlet client's builder,
3. The Servlet builder should return specific subclasses in its methods, because you have to call `.SetRequestDetails(request)` *first* or it won't work

**Comment by fundead** [comment] 2015-04-16 23:21
Just to clarify:

1. messageBuilderForException() should take a Throwable, call `RaygunServletMessageBuilder.New().SetRequestDetails()...Build()` (with all the various parts of the message set, request, env, machineName etc), then return the resulting RaygunMessage? Or just call `.New()`?

2. This should be by design as core.RaygunClient is built without the reference to `javax.servlet.http.HttpServletRequest`, as otherwise non-web projects would need to have a server on their classpath, or import the Maven deps even if they weren't otherwise used. The RaygunServletClient specifically does have this dependency (and the Play 2 client has its own Request object reference yet again) as it is used.
The non-servlet core.RaygunClient has no concept of web requests for that reason, to avoid the dependency -  if this seems wrong let me know.

3. Just modified BuildServletMessage quickly to test this:

```java
RaygunServletMessageBuilder.New()
            //.SetRequestDetails(servletRequest)
            .SetEnvironmentDetails()
            .SetMachineName(InetAddress.getLocalHost().getHostName())
            .SetExceptionDetails(throwable)
            .SetClientDetails()
            .SetVersion(_version)
            .SetUser(_user)
            .Build();
```

and that builds and sends the RaygunMessage as expected without setting the request at all. The New() instantiates the RaygunServletMessageBuilder, the inherited methods set their props then Build() sets and returns the final RaygunServletMessage so as long as New()'s called first and Build() last this should work - might be a different scenario I haven't repro'd here.

**Comment by mduncan26** [comment] 2019-04-24 02:47
Closing this issue for now. If you wish to see this issue addressed please create a new issue or post within our forums (https://raygun.com/forums). Thank you.

**Closed by mduncan26** 2019-04-24 02:47 UTC
